In [0]:
from google.colab import drive
drive.mount('/content/gdrive/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [0]:
cd /content/gdrive/My\ Drive/vip2

/content/gdrive/My Drive/vip2


In [0]:
import numpy as np

In [0]:
train_features_places = np.load('vgg_places_train_features.npy')
train_features_da     = np.load('vgg_da_train_features.npy')
val_features_places  = np.load('vgg_places_val_features.npy')
val_features_da      = np.load('vgg_da_val_features.npy')

trian_label_places = np.load('vgg_places_train_labels.npy')
test_label_places  = np.load('vgg_places_val_labels.npy')

In [0]:
train_features = np.hstack((train_features_places,train_features_da))
val_features = np.hstack((val_features_places, val_features_da))
train_labels = trian_label_places
val_labels = test_label_places

In [0]:
train_features.shape

(6600, 50176)

In [0]:
train_labels = np.argmax(train_labels, axis=1)

In [0]:
from sklearn import svm
clf = svm.SVC(gamma='scale', kernel='linear')
#nsamples, nx, ny = train_features.shape
#train_features = train_dataset.reshape((nsamples,nx*ny))

clf.fit(train_features, train_labels)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
  predictions = clf.predict(val_features)


AxisError: ignored

In [0]:
y_true = np.argmax(val_labels, axis=1)

In [0]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

def scores(y_true,y_pred):
  accuracy = accuracy_score(y_true,y_pred)
  precision = precision_score(y_true,y_pred,average='macro')
  recall = recall_score(y_true,y_pred,average='macro')
  f1 = f1_score(y_true,y_pred,average='macro')
  confusionmatrix = confusion_matrix(y_true, y_pred)
  print("Accuracy:  {}".format(accuracy))
  print("Precision: {}".format(precision))
  print("Recall:    {}".format(recall))
  print("F1:        {}".format(f1))
  print("Confusion matrix:\n{}".format(confusionmatrix))

In [0]:
val_labels.shape

(1800, 12)

In [0]:
print(y_true.shape)
print(predictions.shape)

(1800,)
(1800,)


In [0]:
scores(y_true,predictions)

Accuracy:  0.8161111111111111
Precision: 0.8199941693767175
Recall:    0.8161111111111112
F1:        0.8162128783826504
Confusion matrix:
[[138   0   2   1   0   0   3   0   0   0   4   2]
 [  2 131   0   0   0   9   0   0   1   6   1   0]
 [  3   0 133   0   1   0   0   0   7   0   0   6]
 [  1   0   5 119   0   0   1   1   6   6   8   3]
 [  0   1   1   0 142   0   0   0   1   0   1   4]
 [  0   6   0   2   0 136   0   0   1   5   0   0]
 [ 13   0   0   0   0   0 129   1   0   0   5   2]
 [  6   0   2   2   0   1   4 106   3   1  11  14]
 [  2   2   6   0   0   0   0   1 123   0   6  10]
 [  1   8   4   1   4   7   0   1   4 107   4   9]
 [  3   0   1   7   3   0   0   3  12   3 101  17]
 [  4   0   1   0   9   0   2  20   5   0   5 104]]
