In [0]:
import cv2
import numpy as np

from keras.applications import VGG16
from keras.utils import to_categorical
from keras.preprocessing.image import ImageDataGenerator, load_img
import keras


Using TensorFlow backend.


In [0]:

vgg_conv = VGG16(weights='imagenet',
                 include_top=False,
                input_shape=(224,224,3))







58892288/58889256 [==============================] - 1s 0us/step




In [0]:
from google.colab import drive
drive.mount('/content/gdrive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive/


In [0]:
#cd /content/gdrive/My Drive/Colab Notebooks/vip2/NWPU-RESISC12
#cd /content/gdrive/My Drive/Colab Notebooks/vip2
cd /content/gdrive/My\ Drive/vip2

/content/gdrive/My Drive/vip2


In [0]:
train_dir = 'NWPU-RESISC12/train'
validation_dir = 'NWPU-RESISC12/test'
image_size = 224
nTrain = 6600
nTest = 1800

In [0]:
from keras.preprocessing.image import ImageDataGenerator
# Train :: Extract Features
datagen = ImageDataGenerator(rescale=1./255)
batch_size = 20

train_features = np.zeros(shape=(nTrain, 7, 7, 512))
train_labels = np.zeros(shape=(nTrain,12))

train_generator = datagen.flow_from_directory(
    train_dir,
    target_size=(image_size, image_size),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=True)

i = 0
for inputs_batch, labels_batch in train_generator:
    features_batch = vgg_conv.predict(inputs_batch)
    train_features[i*batch_size:(i+1)*batch_size]=features_batch
    train_labels[i*batch_size:(i+1)*batch_size]=labels_batch
    i+=1
    print(i,end=' ')
    if i*batch_size >= nTrain:
        break
print('\Done')
train_features = np.reshape(train_features, (nTrain, 7 * 7 * 512))

Found 6600 images belonging to 12 classes.


KeyboardInterrupt: ignored

In [0]:
import pickle
with open('VGG_Bottleneck_Train_Features.pkl','wb') as handle:
    pickle.dump(train_features, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open('VGG_Bottleneck_Train_Labels.pkl','wb') as handle:
    pickle.dump(train_labels, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [0]:
cd /content/gdrive/My Drive/Colab Notebooks/vip2

/content/gdrive/My Drive/Colab Notebooks/vip2


In [0]:
ls -l

total 6115586
-rw------- 1 root root     578389 Oct  8 08:31  BOW.ipynb
-rw------- 1 root root      33234 Oct  7 21:43  bow_vgg.ipynb
-rw------- 1 root root      25760 Oct  7 09:27  codebook.pkl
-rw------- 1 root root  459836412 Oct  7 07:26  descriptors_test.npy
-rw------- 1 root root 1776013746 Oct  7 08:15  descriptors_train.npy
-rw------- 1 root root    3679898 Oct  8 07:59  Lab12.ipynb
drwx------ 2 root root       4096 Oct  7 05:22  NWPU-RESISC12/
-rw------- 1 root root  105571978 Sep 30 04:16  NWPUvip.zip
drwx------ 2 root root       4096 Oct  5 07:54  __pycache__/
-rw------- 1 root root  205567512 Oct  7 09:01  res-classifier.h5
-rw------- 1 root root      55281 Oct  7 01:36  RES_FineTune.ipynb
-rw------- 1 root root   94967248 Oct  8 09:05  ResNetFineTune.h5
-rw------- 1 root root  505679064 Oct  7 09:59  ResNetFineTune_weights.h5
-rw------- 1 root root     140278 Oct  8 03:51  restnet.ipynb
-rw------- 1 root root      11689 Oct  5 08:03  vgg16_places_365.py
-rw------- 1 root r

In [0]:
import pickle
train_features = np.zeros((nTrain,7*7*512))
train_labels = np.zeros((nTrain,12))

In [0]:
import pickle
with open('VGG_Bottleneck_Train_Features.pkl','rb') as handle:
    train_features = pickle.load(handle)
with open('VGG_Bottleneck_Train_Labels.pkl','rb') as handle:
    train_labels = pickle.load(handle)

In [0]:
test_features = np.zeros(shape=(nTest, 7, 7, 512))
test_labels = np.zeros(shape=(nTest,12))

test_generator = datagen.flow_from_directory(
    test_dir,
    target_size=(image_size, image_size),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False)

i = 0
for inputs_batch, labels_batch in test_generator:
    features_batch = vgg_conv.predict(inputs_batch)
    test_features[i * batch_size : (i + 1) * batch_size] = features_batch
    test_labels[i * batch_size : (i + 1) * batch_size] = labels_batch
    i += 1
    if i * batch_size >= nTest:
        break

test_features = np.reshape(test_features, (nTest, 7 * 7 * 512))

In [0]:
import pickle
with open('VGG_Bottleneck_Test_Features.pkl','wb') as handle:
    pickle.dump(test_features, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open('VGG_Bottleneck_Test_Labels.pkl','wb') as handle:
    pickle.dump(test_labels, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [0]:
import pickle
with open('VGG_Bottleneck_Test_Features.pkl','rb') as handle:
    test_features = pickle.load(handle)
with open('VGG_Bottleneck_Test_Labels.pkl','rb') as handle:
    test_labels = pickle.load(handle)

In [0]:
print('train:',train_features.shape)
print('test:',test_features.shape)

print('train_label:',train_labels.shape)
print('test_label:',test_labels.shape)

train: (6600, 25088)
test: (1800, 25088)
train_label: (6600, 12)
test_label: (1800, 12)


In [0]:
y_true = []
for i in train_labels:
    y_true.append(np.argmax(i))
y_true

[1,
 8,
 4,
 10,
 11,
 5,
 7,
 8,
 1,
 5,
 2,
 8,
 3,
 9,
 0,
 5,
 2,
 5,
 2,
 7,
 0,
 2,
 9,
 8,
 0,
 5,
 11,
 6,
 3,
 1,
 2,
 9,
 3,
 1,
 7,
 2,
 5,
 2,
 0,
 3,
 5,
 6,
 9,
 2,
 7,
 11,
 9,
 3,
 10,
 11,
 7,
 10,
 0,
 2,
 11,
 11,
 1,
 3,
 4,
 0,
 9,
 2,
 4,
 4,
 6,
 1,
 2,
 2,
 4,
 10,
 3,
 7,
 6,
 5,
 4,
 0,
 11,
 2,
 0,
 8,
 1,
 9,
 7,
 8,
 1,
 9,
 8,
 6,
 7,
 8,
 1,
 5,
 7,
 3,
 3,
 9,
 1,
 9,
 10,
 6,
 10,
 4,
 6,
 1,
 1,
 8,
 1,
 0,
 4,
 2,
 5,
 9,
 7,
 0,
 4,
 9,
 11,
 8,
 1,
 10,
 10,
 11,
 2,
 5,
 1,
 0,
 10,
 7,
 0,
 0,
 4,
 11,
 10,
 3,
 2,
 5,
 7,
 10,
 4,
 11,
 7,
 2,
 4,
 10,
 4,
 1,
 8,
 9,
 8,
 3,
 5,
 10,
 6,
 10,
 3,
 10,
 4,
 6,
 9,
 2,
 4,
 9,
 7,
 6,
 1,
 8,
 2,
 10,
 4,
 11,
 9,
 4,
 7,
 7,
 4,
 8,
 1,
 7,
 8,
 1,
 8,
 3,
 8,
 7,
 8,
 11,
 3,
 2,
 3,
 2,
 1,
 9,
 9,
 4,
 9,
 0,
 7,
 3,
 8,
 4,
 4,
 0,
 1,
 1,
 2,
 1,
 0,
 6,
 3,
 4,
 3,
 8,
 4,
 10,
 2,
 5,
 2,
 9,
 9,
 6,
 5,
 6,
 7,
 10,
 7,
 6,
 7,
 10,
 3,
 6,
 4,
 8,
 7,
 1,
 4,
 6,
 0,
 3,
 5,
 9,
 8,
 8,


In [0]:
# SVM
from sklearn import svm
clf = svm.SVC(gamma='scale', decision_function_shape='ovo')
clf.fit(train_features, y_true)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
clf.predict([test_features[0]])

array([0])

In [0]:
test_true = []
for i in test_labels:
    test_true.append(np.argmax(i))


In [0]:
len(test_true)

1800

In [0]:
test_pred = []
for i in range(len(test_true)):
    test_pred.append(clf.predict([test_features[i]])[0])

In [0]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

accuracy = accuracy_score(test_true,test_pred)
precision = precision_score(test_true,test_pred,average='micro')
recall = recall_score(test_true,test_pred,average='micro')
f1 = f1_score(test_true,test_pred,average='micro')
print("Accuracy:  {}".format(accuracy))
print("Precision: {}".format(precision))
print("Recall:    {}".format(recall))
print("F1:        {}".format(f1))

Accuracy:  0.8205555555555556
Precision: 0.8205555555555556
Recall:    0.8205555555555556
F1:        0.8205555555555556


In [0]:
cm = confusion_matrix(test_true,test_pred)
print(cm)

[[126   0   6   0   1   0   6   2   2   0   6   1]
 [  1 129   0   0   0  12   0   0   1   4   3   0]
 [  4   0 119   0   3   0   0   0  18   0   1   5]
 [  4   3   2 132   0   1   0   1   2   1   2   2]
 [  0   0   0   0 137   0   0   0   0   0   1  12]
 [  0  10   0   0   0 134   0   0   0   4   2   0]
 [  7   0   1   0   0   0 133   2   0   0   6   1]
 [  2   0   4   2   1   0   4 108   2   0   9  18]
 [  2   0   6   0   3   0   0   1 116   0  10  12]
 [  4   3   1   2   2   3   1   5   0 114   5  10]
 [  6   2   1   5   1   0   0   2   5   2 117   9]
 [  2   0   4   1   9   0   0  10   6   0   6 112]]


In [0]:
labels=['beach','commercial_area','desert','farmland','forest','industrial_area','island','lake','mountain','residential','river','wetland']
confusion_matrix(test_true,test_pred)